config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  mount ActionCable.server => '/cable'


  resources :channels
  resources :offers
  resources :profiles, except: [:index, :create, :new] do
    member do
      get :public
    end
  end
  resources :offers do
    member do
      post 'join', to: 'crew_merger#join_crew'
      post 'leave', to: 'crew_merger#leave_crew'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/channel.rb
class Channel < ApplicationRecord
  belongs_to :user
  belongs_to :offer
  has_many :messages, dependent: :destroy
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :require_login
  before_action :set_channel, only: [:edit, :update, :destroy]

  # GET /channels
  # GET /channels.json
  def index
    # Loading the channel linked to the offer of the current users
    @channels = current_user_channels
  end

  # GET /channels/1
  # GET /channels/1.json
  def show
    @channel = current_user_channels
                   .includes(:messages)
                   .includes(offer: :users)
                   .includes(messages: :user)
                   .where(id: params[:id])
                   .first

    @message = Message.new
  end

  # GET /channels/new
  def new
    @channel = Channel.new
  end

  # GET /channels/1/edit
  def edit
  end

  # POST /channels
  # POST /channels.json
  def create
    @channel = current_user.channels.build(channel_params)

    respond_to do |format|
      if @channel.save
        format.html { redirect_to @channel, notice: 'Channel was successfully created.' }
        format.json { render :show, status: :created, location: @channel }
      else
        format.html { render :new }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /channels/1
  # PATCH/PUT /channels/1.json
  def update
    respond_to do |format|
      if @channel.update(channel_params)
        format.html { redirect_to @channel, notice: 'Channel was successfully updated.' }
        format.json { render :show, status: :ok, location: @channel }
      else
        format.html { render :edit }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /channels/1
  # DELETE /channels/1.json
  def destroy
    @channel.destroy
    respond_to do |format|
      format.html { redirect_to channels_url, notice: 'Channel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def current_user_channels
      Channel.where(offer_id: current_user.offers.pluck(:id))
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_channel
      @channel = current_user_channels.where(id: params[:id]).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def channel_params
      params.require(:channel).permit(:title, :user_id)
    end
end

app/views/channels/_form.html.haml
= form_for @channel do |f|
  - if @channel.errors.any?
    #error_explanation
      %h2= "#{pluralize(@channel.errors.count, "error")} prohibited this channel from being saved:"
      %ul
        - @channel.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title

  .actions
    = f.submit 'Save'

app/views/channels/edit.html.haml
%h1 Editing channel

= render 'form'

= link_to 'Show', @channel
\|
= link_to 'Back', channels_path

app/views/channels/index.html.haml
%h1 Listing channels

%table
  %thead
    %tr
      %th Title
      %th
      %th
      %th

  %tbody
    - @channels.each do |channel|
      %tr
        %td= channel.title
        %td= link_to 'Show', channel
        - if channel.user_id == current_user.id
          %td= link_to 'Edit', edit_channel_path(channel)
          %td= link_to 'Destroy', channel, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Channel', new_channel_path

app/views/channels/new.html.haml
%h1 New channel

= render 'form'

= link_to 'Back', channels_path

app/views/channels/show.html.haml
%p
  %b= @channel.title
  %span= @channel.created_at

%p
  Conversation for
  = link_to @channel.offer.name, @channel.offer
  with
  - @channel.offer.users.map do |u|
    - if u.id == current_user.id
      %span Me
    - else
      = link_to u.email, public_profile_url(u)

#messages{'data-channel-room-id':"#{@channel.id}", style:'overflow-y: scroll; height:400px;'}
  - @channel.messages.each do |message|
    = render 'messages/message', message: message


= form_for @message, url: '#' do |f|
  = f.label :body
  = f.text_area :body, class: 'form-control'
  = f.submit "Post"

= link_to 'Edit', edit_channel_path(@channel)
\|
= link_to 'Back', channels_path