config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  mount ActionCable.server => '/cable'


  resources :channels
  resources :offers
  resources :profiles, except: [:index, :create, :new] do
    member do
      get :public
    end
  end
  resources :offers do
    member do
      post 'join', to: 'crew_merger#join_crew'
      post 'leave', to: 'crew_merger#leave_crew'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :require_login, except: [:public]
  before_action :set_profile, only: [:show, :edit]

  def public
    @profile = User.where(id: params[:id]).includes(:images).first
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if current_user.update(profile_params)
        format.html { redirect_to profile_path, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: current_user }
      else
        format.html { render :edit }
        format.json { render json: current_user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
  end

  private

  def set_profile
    @profile = current_user
  end

  def profile_params
    params.require(:user).permit(:email, :password, :sex, :orientation, :date_of_birth, :more_about_me,
                                 :languages, :is_studying, :guilty_pleasure, :best_recipe,
                                 :voluntary_work, :favorite_quote, :heroic_thing, :happiest_moment,
                                 :world_better_place, :top_music, :top_movies, :top_series, :top_books,
                                 :top_games, :hobbies, :nick_name, :first_name, :last_name, :company, :school,
                                 :social_networks, :nationality, :three_wishes,
                                 images_attributes: [:id, :file, :caption])
  end
end

app/views/profiles/_form.html.haml
= form_for profile, url: {action: 'update'}, html: { multipart: true } do  |f|

  = render 'profile_fields', f: f

  .actions
    = f.submit

app/views/profiles/_image_fields.html.haml
.nested-fields
  .field
    = f.label :file
    = f.file_field :file

  .field
    = f.label :caption
    = f.text_field :caption

  = link_to_remove_association 'remove image', f

app/views/profiles/_offers_list.html.haml
%table
  %thead
    %tr
      %th Budget
      %th Nb wanted people
      %th Start date
      %th End date
      %th Name
      %th Situation
      %th{:colspan => "3"}
  %tbody
    - offers.each do |offer|
      %tr
        %td= offer.budget
        %td= offer.nb_wanted_people
        %td= offer.start_date
        %td= offer.end_date
        %td= offer.name
        %td= offer.situation
        %td= link_to 'Show', offer
        %td= link_to 'Edit', edit_offer_path(offer)
        %td= link_to 'Destroy', offer, method: :delete, data: { confirm: 'Are you sure?' }

app/views/profiles/_profile.html.haml
%h3 Images
%p
  - if profile.images.present?
    - profile.images.each do |image|
      %p
        %span= image_tag image.file.url(:medium)
        %span= image.caption

%h3 Profile
%p
  %strong email
  = profile.email

%p
  %strong First name
  = profile.first_name

%p
  %strong Last name
  = profile.last_name

%p
  %strong nick name
  = profile.nick_name

%p
  %strong Sex
  = profile.sex

%p
  %strong Orientation
  = profile.orientation

%p
  %strong Date of birth
  = profile.date_of_birth

%p
  %strong More about me
  = profile.more_about_me

%p
  %strong Languages
  = profile.languages

%p
  %strong Is studying
  = profile.is_studying

%p
  %strong Guilty pleasure
  = profile.guilty_pleasure

%p
  %strong Best recipe
  = profile.best_recipe

%p
  %strong Voluntary work
  = profile.voluntary_work

%p
  %strong Favorite quote
  = profile.favorite_quote

%p
  %strong Heroic thing
  = profile.heroic_thing

%p
  %strong Happiest moment
  = profile.happiest_moment

%p
  %strong World better place
  = profile.world_better_place

%p
  %strong Top music
  = profile.top_music

%p
  %strong Top movies
  = profile.top_movies

%p
  %strong Top series
  = profile.top_series

%p
  %strong Top books
  = profile.top_books

%p
  %strong Top games
  = profile.top_games

%p
  %strong Hobbies
  = profile.hobbies

%p
  %strong Company
  = profile.company

%p
  %strong School
  = profile.school

%p
  %strong Social networks
  = profile.social_networks

%p
  %strong Nationality
  = profile.nationality

%p
  %strong Three wishes
  = profile.three_wishes

app/views/profiles/_profile_fields.html.haml
.nested-fields
  = f.fields_for :images do |f_image|
    = render 'image_fields', f: f_image
  .links
    = link_to_add_association 'Add image', f, :images

  .field
    = f.label :email
    = f.email_field :email

  .field
    = f.label :nick_name
    = f.text_field :nick_name

  .field
    = f.label :first_name
    = f.text_field :first_name

  .field
    = f.label :last_name
    = f.text_field :last_name

  .field
    = f.label :sex
    = f.number_field :sex

  .field
    = f.label :orientation
    = f.number_field :orientation

  .field
    = f.label :date_of_birth
    = f.date_field :date_of_birth

  .field
    = f.label :more_about_me
    = f.text_field :more_about_me

  .field
    = f.label :languages
    = f.text_field :languages

  .field
    = f.label :is_studying
    = f.check_box :is_studying

  .field
    = f.label :guilty_pleasure
    = f.text_field :guilty_pleasure

  .field
    = f.label :best_recipe
    = f.text_field :best_recipe

  .field
    = f.label :voluntary_work
    = f.text_field :voluntary_work

  .field
    = f.label :favorite_quote
    = f.text_field :favorite_quote

  .field
    = f.label :heroic_thing
    = f.text_field :heroic_thing

  .field
    = f.label :happiest_moment
    = f.text_field :happiest_moment

  .field
    = f.label :world_better_place
    = f.text_field :world_better_place

  .field
    = f.label :top_music
    = f.text_field :top_music

  .field
    = f.label :top_movies
    = f.text_field :top_movies

  .field
    = f.label :top_series
    = f.text_field :top_series

  .field
    = f.label :top_books
    = f.text_field :top_books

  .field
    = f.label :top_games
    = f.text_field :top_games

  .field
    = f.label :hobbies
    = f.text_field :hobbies

  .field
    = f.label :company
    = f.text_field :company

  .field
    = f.label :school
    = f.text_field :school

  .field
    = f.label :social_networks
    = f.text_field :social_networks

  .field
    = f.label :nationality
    = f.text_field :nationality

  .field
    = f.label :three_wishes
    = f.text_field :three_wishes

app/views/profiles/destroy.html.haml
%h1 Profile#destroy
%p Find me in app/views/profile/destroy.html.haml

app/views/profiles/edit.html.haml
%h1 Edit profile

#{link_to 'Back', profile_path}

= render 'profiles/form', profile: @profile

app/views/profiles/public.html.haml
%h3 Public profile

= render 'profile', profile: @profile

app/views/profiles/show.html.haml
- if signed_in?
  = link_to 'Edit profile', edit_profile_path

= render 'offers_list', offers: @profile.offers
= render 'profile', profile: @profile