config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  mount ActionCable.server => '/cable'


  resources :channels
  resources :offers
  resources :profiles, except: [:index, :create, :new] do
    member do
      get :public
    end
  end
  resources :offers do
    member do
      post 'join', to: 'crew_merger#join_crew'
      post 'leave', to: 'crew_merger#leave_crew'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/offer.rb
class Offer < ApplicationRecord
  has_many :teams, dependent: :destroy
  has_many :users, through: :teams, dependent: :destroy
  has_many :images, as: :imageable, dependent: :destroy
  has_many :channels, dependent: :destroy
  has_one :place, dependent: :destroy

  accepts_nested_attributes_for :place, :images, :users

  after_create_commit :create_channel

  def self.default_scope
    where(blocked:false).group('offers.id, offers.created_at').order('offers.created_at DESC')
  end

  private

  def create_channel
    # crée une conversation, on ajoute les users dedans
    title = "Offer : #{self.name}, #{self.budget} #{self.start_date} #{self.end_date}"
    # current connected user, is always the last inserted
    current_user_id = self.users.last.id
    Channel.create!(user_id: current_user_id, title: title, offer_id: self.id)
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :require_login
  before_action :set_offer, only: [:show]
  before_action :set_offer_for_user, only: [:edit, :update, :destroy]

  # GET /offers
  # GET /offers.json
  def index
    if search_params.present?
      @offers = SearchHelper.new(search_params).search
      @params = search_params
    else
      @offers = Offer.where(situation:'homeless').all
    end
  end

  # GET /offers/1
  # GET /offers/1.json
  def show
  end

  # GET /offers/new
  def new
    @offer = Offer.new
  end

  # GET /offers/1/edit
  def edit
  end

  # POST /offers
  # POST /offers.json
  def create
    ActiveRecord::Base.transaction do
      @offer = Offer.new(offer_params)

      @offer.users << current_user
      respond_to do |format|
        if @offer.save

          # @offer.users.each do |u|
          #   ClearanceMailer.change_password(u).deliver_later
          # end

          format.html { redirect_to @offer, notice: 'Offer was successfully created.' }
          format.json { render :show, status: :created, location: @offer }
        else
          format.html { render :new }
          format.json { render json: @offer.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /offers/1
  # PATCH/PUT /offers/1.json
  def update
    respond_to do |format|
      if @offer.update(offer_params)
        format.html { redirect_to @offer, notice: 'Offer was successfully updated.' }
        format.json { render :show, status: :ok, location: @offer }
      else
        format.html { render :edit }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer.destroy
    respond_to do |format|
      format.html { redirect_to profile_path, notice: 'Offer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer
      @offer = Offer.includes(:images)
                   .includes(users: :images)
                   .includes(:place)
                   .where(id: params[:id])
                   .first
    end

    def set_offer_for_user
      @offer = current_user.offers
                   .includes(:images)
                   .includes(:place)
                   .where(id: params[:id]).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offer_params
      params.require(:offer).permit(:budget, :nb_wanted_people, :start_date, :end_date, :is_mock,
                                    :prefered_sex, :name, :activities, :ritual, :partying, :nature,
                                    :situation, :blocked, :never_do, :dream_flatmate,
                                    place_attributes: [:id, :nb_bathrooms, :nb_toilets, :internet, :dishwasher,
                                                        :ac, :parking, :tv, :playstation, :satellite,
                                                        :xbox, :wii, :smoking, :animals, :caution_price,
                                                        :electricity_price, :internet_price,
                                                        :heating_price, :detail, :title,
                                                        :nb_places_availables, :property_type, :surface,
                                                        :other_stuff, :monthly_rent_price, :total_price],
                                    images_attributes: [:id, :file, :caption],
                                    users_attributes: [:id, :email, :password, :sex, :orientation, :date_of_birth, :more_about_me,
                                                       :languages, :is_studying, :guilty_pleasure, :best_recipe,
                                                       :voluntary_work, :favorite_quote, :heroic_thing, :happiest_moment,
                                                       :world_better_place, :top_music, :top_movies, :top_series, :top_books,
                                                       :top_games, :hobbies, :nick_name, :first_name, :last_name, :company, :school,
                                                       :social_networks, :nationality, :three_wishes,
                                                       images_attributes: [:id, :file, :caption]])
    end

    def search_params
      params.permit(:situation, :start_date, :end_date, :min_price, :max_price)
    end
end

app/helpers/offers_helper.rb
module OffersHelper

end

app/views/offers/_feed_navbar.html.haml
.feed_nav_bar
  .grid.grid_wrapper
    .row
      .all-16.feed_nav_bar__container
        .feed_nav_bar__col
          %span.small.filters
            %i.icon.i_plus
            %span Search
        .feed_nav_bar__col
          = link_to offers_path(situation:'homeless'), class: @params['situation'] == 'homeless' ? 'active' : nil do
            %i.icon.i_homeless
            %span Homeless
        .feed_nav_bar__col
          = link_to offers_path(situation:'existing'), class: @params['situation'] == 'existing' ? 'active' : nil do
            %i.icon.i_crew
            %span Existing Flatshares
        .feed_nav_bar__col
          = link_to offers_path(situation:'place'), class: @params['situation'] == 'place' ? 'active' : nil do
            %i.icon.i_place_on_rent
            %span Places to rent
        .feed_nav_bar__col
          %span.small.help
            %i.icon.i_plus
            %span Help

app/views/offers/_form.html.haml
= form_for offer, html: { multipart: true } do  |f|
  - if offer.errors.any?
    #error_explanation
      %h2
        = pluralize(offer.errors.count, "error")
        prohibited this offer from being saved:
      %ul
        - offer.errors.full_messages.each do |message|
          %li= message

  = f.fields_for :users, offer.users do |f_user|
    = render 'user_fields', f: f_user
  .links
    = link_to_add_association 'Add user', f, :users


  = f.fields_for :images, offer.images do |f_image|
    = render 'offers/image_fields', f: f_image
  .links
    = link_to_add_association 'Add image', f, :images

  = f.fields_for :place , offer.place do |place_field|
    = render 'offers/place_fields', f: place_field
  .links
    = link_to_add_association 'Add a place', f, :place, force_non_association_create: true

  .field
    = f.label :budget
    = f.text_field :budget
  .field
    = f.label :nb_wanted_people
    = f.number_field :nb_wanted_people
  .field
    = f.label :start_date
    = f.date_select :start_date
  .field
    = f.label :end_date
    = f.date_select :end_date
  .field
    = f.label :never_do
    = f.text_field :never_do
  .field
    = f.label :dream_flatmate
    = f.text_field :dream_flatmate
  .field
    = f.label :prefered_sex
    = f.number_field :prefered_sex
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :activities
    = f.text_field :activities
  .field
    = f.label :ritual
    = f.text_field :ritual
  .field
    = f.label :partying
    = f.text_field :partying
  .field
    = f.label :nature
    = f.text_field :nature
  .field
    = f.label :situation
    = f.select :situation, options_for_select(['homeless', 'place on rent', 'existing'], 'existing')

  .actions
    = f.submit

app/views/offers/_image_fields.html.haml
.nested-fields
  .field
    = f.label :file
    = f.file_field :file

  .field
    = f.label :caption
    = f.text_field :caption

  = link_to_remove_association 'remove image', f

app/views/offers/_place_fields.html.haml
.nested-fields
  .field
    = f.label :nb_bathrooms
    = f.number_field :nb_bathrooms

  .field
    = f.label :nb_toilets
    = f.number_field :nb_toilets

  .field
    = f.label :internet
    = f.check_box :internet

  .field
    = f.label :dishwasher
    = f.check_box :dishwasher

  .field
    = f.label :ac
    = f.check_box :ac

  .field
    = f.label :parking
    = f.check_box :parking

  .field
    = f.label :tv
    = f.check_box :tv

  .field
    = f.label :playstation
    = f.check_box :playstation

  .field
    = f.label :xbox
    = f.check_box :xbox

  .field
    = f.label :smoking
    = f.check_box :smoking

  .field
    = f.label :animals
    = f.check_box :animals

  .field
    = f.label :satellite
    = f.check_box :satellite

  .field
    = f.label :wii
    = f.check_box :wii

  .field
    = f.label :caution_price
    = f.text_field :caution_price

  .field
    = f.label :electricity_price
    = f.text_field :electricity_price

  .field
    = f.label :internet_price
    = f.text_field :internet_price

  .field
    = f.label :heating_price
    = f.text_field :heating_price

  .field
    = f.label :monthly_rent_price
    = f.text_field :monthly_rent_price

  .field
    = f.label :total_price
    = f.text_field :total_price

  .field
    = f.label :detail
    = f.text_field :detail

  .field
    = f.label :title
    = f.text_field :title

  .field
    = f.label :nb_places_availables
    = f.number_field :nb_places_availables

  .field
    = f.label :property_type
    = f.text_field :property_type

  .field
    = f.label :surface
    = f.number_field :surface

  .field
    = f.label :other_stuff
    = f.text_field :other_stuff

  = link_to_remove_association 'Remove place', f

app/views/offers/_user_fields.html.haml
.nested-fields
  = f.fields_for :images do |f_image|
    = render 'image_fields', f: f_image
  .links
    = link_to_add_association 'Add image', f, :images

    = f.hidden_field :password, value: 'azertyuiop'

  .field
    = f.label :email
    = f.email_field :email

  .field
    = f.label :nick_name
    = f.text_field :nick_name

  .field
    = f.label :first_name
    = f.text_field :first_name

  .field
    = f.label :last_name
    = f.text_field :last_name

  .field
    = f.label :sex
    = f.number_field :sex

  .field
    = f.label :orientation
    = f.number_field :orientation

  .field
    = f.label :date_of_birth
    = f.date_field :date_of_birth

  .field
    = f.label :more_about_me
    = f.text_field :more_about_me

  .field
    = f.label :languages
    = f.text_field :languages

  .field
    = f.label :is_studying
    = f.check_box :is_studying

  .field
    = f.label :guilty_pleasure
    = f.text_field :guilty_pleasure

  .field
    = f.label :best_recipe
    = f.text_field :best_recipe

  .field
    = f.label :voluntary_work
    = f.text_field :voluntary_work

  .field
    = f.label :favorite_quote
    = f.text_field :favorite_quote

  .field
    = f.label :heroic_thing
    = f.text_field :heroic_thing

  .field
    = f.label :happiest_moment
    = f.text_field :happiest_moment

  .field
    = f.label :world_better_place
    = f.text_field :world_better_place

  .field
    = f.label :top_music
    = f.text_field :top_music

  .field
    = f.label :top_movies
    = f.text_field :top_movies

  .field
    = f.label :top_series
    = f.text_field :top_series

  .field
    = f.label :top_books
    = f.text_field :top_books

  .field
    = f.label :top_games
    = f.text_field :top_games

  .field
    = f.label :hobbies
    = f.text_field :hobbies

  .field
    = f.label :company
    = f.text_field :company

  .field
    = f.label :school
    = f.text_field :school

  .field
    = f.label :social_networks
    = f.text_field :social_networks

  .field
    = f.label :nationality
    = f.text_field :nationality

  .field
    = f.label :three_wishes
    = f.text_field :three_wishes

  = link_to_remove_association 'Remove user', f

app/views/offers/edit.html.haml
%h1 Editing Offer

= link_to 'Show', @offer

#{link_to 'Back', offers_path}


= render 'form', offer: @offer

app/views/offers/index.html.haml
.feed_layer
  = render 'offers/feed_navbar'
  .feed_layer__content
    .left

app/views/offers/new.html.haml
%h1 New Offer
= render 'form', offer: @offer
= link_to 'Back', offers_path

app/views/offers/show.html.haml
#{link_to 'Back', offers_path}


- if @offer.users.include? current_user
  = link_to 'Leave this crew', leave_offer_path, method: :post, data: { confirm: 'This action wil blablabla' }
- else
  = link_to 'Join this crew', join_offer_path, method: :post, data: { confirm: 'This action wil blablabla' }

%h3 Crew

- @offer.users.each do |user|
  %p
    - if user.id == current_user.id
      Me
    - else
      - if user.images.present?
        %span= image_tag user.images.first.file.url(:thumb)
      = link_to user.email, public_profile_url(user)

%h3 Images
%p
  - @offer.images.each do |image|
    %p
      %span= image_tag image.file.url(:medium)
      %span= image.caption


- if @offer.place.present?
  %h3 Place

  %p
    %strong Nb bathrooms
    = @offer.place.nb_bathrooms

  %p
    %strong Nb toilets
    = @offer.place.nb_toilets

  %p
    %strong Internet
    = @offer.place.internet

  %p
    %strong Dishwasher
    = @offer.place.dishwasher

  %p
    %strong Ac
    = @offer.place.ac

  %p
    %strong Parking
    = @offer.place.parking

  %p
    %strong Tv
    = @offer.place.tv

  %p
    %strong Playstation
    = @offer.place.playstation

  %p
    %strong Xbox
    = @offer.place.xbox

  %p
    %strong Wii
    = @offer.place.wii

  %p
    %strong Smoking
    = @offer.place.smoking

  %p
    %strong Animals
    = @offer.place.animals

  %p
    %strong Satellite
    = @offer.place.satellite

  %p
    %strong Caution price
    = @offer.place.caution_price

  %p
    %strong Electricity price
    = @offer.place.electricity_price

  %p
    %strong Internet price
    = @offer.place.internet_price

  %p
    %strong Heating price
    = @offer.place.heating_price

  %p
    %strong Monthly price
    = @offer.place.monthly_rent_price

  %p
    %strong Total price
    = @offer.place.total_price

  %p
    %strong Detail
    = @offer.place.detail

  %p
    %strong Title
    = @offer.place.title

  %p
    %strong Nb place available
    = @offer.place.nb_places_availables

  %p
    %strong Property type
    = @offer.place.property_type

  %p
    %strong Other stuff
    = @offer.place.other_stuff
  %p
    %strong Surface
    = @offer.place.surface

%h3 Offer
%p
  %strong Budget:
  = @offer.budget
%p
  %strong Nb wanted people:
  = @offer.nb_wanted_people
%p
  %strong Start date:
  = @offer.start_date
%p
  %strong End date:
  = @offer.end_date
%p
  %strong Is mock:
  = @offer.is_mock
%p
  %strong Prefered sex:
  = @offer.prefered_sex
%p
  %strong Name:
  = @offer.name
%p
  %strong Activities:
  = @offer.activities
%p
  %strong Ritual:
  = @offer.ritual
%p
  %strong Partying:
  = @offer.partying
%p
  %strong Nature:
  = @offer.nature
%p
  %strong Situation:
  = @offer.situation
%p
  %strong Blocked:
  = @offer.blocked
%p
  %strong Never do:
  = @offer.never_do
%p
  %strong Dream flatmate:
  = @offer.dream_flatmate